### ISSUE TITLE
Add metadata to track external discussion

### ISSUE THREAD

**Issue by killercup** [killercup/scribbles#5]
```
discussions:
  Reddit: ....
  Twitter: ....
  HN: ....
```

and show it as a list below the post. (Steal template from rust.cologne)
